### ISSUE TITLE
Directions for submitting assignment

### ISSUE THREAD

**Issue by pdirmeyer** [aachar5/6801stassignment#3]
You uploaded your notebooks on Blackboard. The assignment asked you to post links to your assignment GitHub pages, so that we could comment via _issues_.

**Comment by aachar5** [comment]
Dear Paul,
I have uploaded it also in my GitHub.

Get Outlook for iOS<https://aka.ms/o0ukef>

From: Paul D. ***@***.***>
Sent: Thursday, September 29, 2022 8:37:55 AM
To: aachar5/6801stassignment ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aachar5/6801stassignment] Directions for submitting assignment (Issue #3)


You uploaded your notebooks on Blackboard. The assignment asked you to post links to your assignment GitHub pages, so that we could comment via issues.

**Comment by pdirmeyer** [comment]
Hi Aasma:

Thank you; we were able to find your assignment on Github, but the links (URL) should have been posted on Blackboard, not the actual Jupyter notebooks.  It was a minor issue.

Regards,
   -Paul

9/29/22, 8:49 AM, "aachar5" ***@***.***>:

Dear Paul,
I have uploaded it also in my GitHub.

Get Outlook for iOS<https://aka.ms/o0ukef>

From: Paul D. ***@***.***>
Sent: Thursday, September 29, 2022 8:37:55 AM
To: aachar5/6801stassignment ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aachar5/6801stassignment] Directions for submitting assignment (Issue #3)


You uploaded your notebooks on Blackboard. The assignment asked you to post links to your assignment GitHub pages, so that we could comment via issues.
